export const ELEGANCE_THEME = {
  "--color-bg": "#FFDBBB",
  "--color-surface": "#CCBEB1",
  "--color-surface-alt": "#FFF5EB",
  "--color-border": "#997E67",
  "--color-text": "#664930",
  "--color-text-muted": "#997E67",
  "--color-accent": "#664930",
  "--color-accent-text": "#FFDBBB",
  "--color-success": "#6B8F5E",
  "--color-warning": "#C4844A",
  "--color-error": "#B85C5C",
  "--color-shadow": "rgba(102, 73, 48, 0.12)",
  "--color-shadow-strong": "rgba(102, 73, 48, 0.22)",
  "--color-hover": "#F5C99A",
  "--color-hover-strong": "#E8B887",
} as const;

export const THEME_PRESETS: Record<string, Record<string, string>> = {
  elegance: { ...ELEGANCE_THEME },
  "elegance-dark": {
    "--color-bg": "#664930",
    "--color-surface": "#997E67",
    "--color-surface-alt": "#553D28",
    "--color-border": "#CCBEB1",
    "--color-text": "#FFDBBB",
    "--color-text-muted": "#CCBEB1",
    "--color-accent": "#FFDBBB",
    "--color-accent-text": "#664930",
    "--color-success": "#A8C99A",
    "--color-warning": "#E8B87A",
    "--color-error": "#E89898",
    "--color-shadow": "rgba(0, 0, 0, 0.18)",
    "--color-shadow-strong": "rgba(0, 0, 0, 0.32)",
    "--color-hover": "#7A5A40",
    "--color-hover-strong": "#8F6848",
  },
  taupe: {
    ...ELEGANCE_THEME,
    "--color-bg": "#CCBEB1",
    "--color-surface": "#FFDBBB",
    "--color-surface-alt": "#FFF5EB",
  },
  mocha: {
    ...ELEGANCE_THEME,
    "--color-bg": "#997E67",
    "--color-surface": "#CCBEB1",
    "--color-surface-alt": "#FFDBBB",
    "--color-text": "#FFF5EB",
    "--color-text-muted": "#FFDBBB",
    "--color-accent": "#664930",
    "--color-accent-text": "#FFDBBB",
    "--color-hover": "#8A6F58",
    "--color-hover-strong": "#755942",
  },
  blue: { ...ELEGANCE_THEME },
  green: {
    ...ELEGANCE_THEME,
    "--color-accent": "#5A7248",
    "--color-success": "#6B8F5E",
  },
  pink: {
    ...ELEGANCE_THEME,
    "--color-accent": "#8F5A5A",
    "--color-hover": "#F0C4C4",
  },
  purple: {
    ...ELEGANCE_THEME,
    "--color-accent": "#6B5A72",
    "--color-hover": "#E8D0F0",
  },
  orange: {
    ...ELEGANCE_THEME,
    "--color-accent": "#8F5A30",
    "--color-warning": "#C4844A",
    "--color-hover": "#F5C99A",
  },
};
