export const ELEGANCE_THEME = {
  "--color-bg": "#FFF0F5",
  "--color-surface": "#FFE4E1",
  "--color-surface-alt": "#FFFFFF",
  "--color-border": "#FCA3B7",
  "--color-text": "#4A1525",
  "--color-text-muted": "#8A4F5F",
  "--color-accent": "#E64980",
  "--color-accent-text": "#FFFFFF",
  "--color-success": "#5BA373",
  "--color-warning": "#E07A3E",
  "--color-error": "#C9405C",
  "--color-shadow": "rgba(74, 21, 37, 0.12)",
  "--color-shadow-strong": "rgba(74, 21, 37, 0.22)",
  "--color-hover": "#FFC2D1",
  "--color-hover-strong": "#FF99B3",
} as const;

export const THEME_PRESETS: Record<string, Record<string, string>> = {
  elegance: { ...ELEGANCE_THEME },
  "elegance-dark": {
    "--color-bg": "#4A1525",
    "--color-surface": "#6E1F37",
    "--color-surface-alt": "#2D0D16",
    "--color-border": "#FCA3B7",
    "--color-text": "#FFF0F5",
    "--color-text-muted": "#FCA3B7",
    "--color-accent": "#FFC2D1",
    "--color-accent-text": "#4A1525",
    "--color-success": "#7BB892",
    "--color-warning": "#F4A373",
    "--color-error": "#DE6B82",
    "--color-shadow": "rgba(0, 0, 0, 0.18)",
    "--color-shadow-strong": "rgba(0, 0, 0, 0.32)",
    "--color-hover": "#5C1A2E",
    "--color-hover-strong": "#6E1F37",
  },
  taupe: {
    ...ELEGANCE_THEME,
    "--color-bg": "#FFD1DC",
    "--color-surface": "#FFE4E1",
    "--color-surface-alt": "#FFF0F5",
  },
  mocha: {
    ...ELEGANCE_THEME,
    "--color-bg": "#8A4F5F",
    "--color-surface": "#FCA3B7",
    "--color-surface-alt": "#FFE4E1",
    "--color-text": "#FFF0F5",
    "--color-text-muted": "#FFE4E1",
    "--color-accent": "#4A1525",
    "--color-accent-text": "#FFF0F5",
    "--color-hover": "#784452",
    "--color-hover-strong": "#663945",
  },
  blue: {
    ...ELEGANCE_THEME,
    "--color-accent": "#5A82A8",
    "--color-hover": "#C4D8F0",
  },
  green: {
    ...ELEGANCE_THEME,
    "--color-accent": "#5BA373",
    "--color-success": "#4D8A61",
    "--color-hover": "#C4F0D5",
  },
  pink: {
    ...ELEGANCE_THEME,
    "--color-accent": "#FF3377",
    "--color-hover": "#FFC2D1",
  },
  purple: {
    ...ELEGANCE_THEME,
    "--color-accent": "#9B59B6",
    "--color-hover": "#E8D0F0",
  },
  orange: {
    ...ELEGANCE_THEME,
    "--color-accent": "#E07A3E",
    "--color-warning": "#C46527",
    "--color-hover": "#F5D4C4",
  },
};
